import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const source = fs.readFileSync('script.js', 'utf8');
const cutoff = source.indexOf("\ndocument.querySelectorAll('[data-add]')");
const ctx = vm.createContext({ localStorage: { getItem: () => null }, crypto: globalThis.crypto, console, setTimeout, clearTimeout });
vm.runInContext(source.slice(0, cutoff), ctx);
const result = vm.runInContext(`(function(){
  update=()=>{}; editorToast=()=>{};
  const layout=makeItem('layout','two');
  const button=makeItem('button','rounded');
  state.items.push(layout,button);
  moveIntoLayout(button.id,layout.id);
  const moved=button.layoutId===layout.id;
  selected=layout.id; duplicate();
  const duplicateLayout=state.items.find(item=>item.id===selected);
  const duplicateChildren=state.items.filter(item=>item.layoutId===duplicateLayout.id);
  copyItem(layout.id); pasteItem();
  const pastedLayout=state.items.find(item=>item.id===selected);
  const pastedChildren=state.items.filter(item=>item.layoutId===pastedLayout.id);
  duplicatePage('home');
  const copiedPage=activePage;
  const pageLayouts=state.items.filter(item=>item.page===copiedPage&&item.type==='layout');
  const pageChildren=state.items.filter(item=>item.page===copiedPage&&item.layoutId);
  const validPageLinks=pageChildren.every(item=>pageLayouts.some(layout=>layout.id===item.layoutId));
  activePage='home'; deleteItem(layout.id);
  return {moved,duplicateChildren:duplicateChildren.length,pastedChildren:pastedChildren.length,validPageLinks,ungrouped:button.layoutId===null};
})()`, ctx);
assert.equal(result.moved, true);
assert.equal(result.duplicateChildren, 1);
assert.equal(result.pastedChildren, 1);
assert.equal(result.validPageLinks, true);
assert.equal(result.ungrouped, true);
console.log('Layout move, duplicate, copy/paste, page duplicate, and delete passed.');
const template = vm.runInContext(`(function(){update=()=>{};editorToast=()=>{};const before=state.pages.length;createTemplatePage('shop');const page=activePage;const items=state.items.filter(item=>item.page===page);const html=items.filter(item=>!item.layoutId).map(exportElement).join('');return {before,after:state.pages.length,title:state.pageTitles[page],count:items.length,hasLayout:html.includes('ui-layout'),hasButton:html.includes('加入购物袋')}})()`, ctx);
assert.equal(template.after, template.before + 3);
assert.equal(template.title, '商品详情');
assert.ok(template.count >= 5 && template.hasLayout && template.hasButton);
const flow = vm.runInContext(`(function(){const ids=state.pages.slice(-3);return {ids,modes:ids.map(id=>state.pageModes[id]),parents:ids.map(id=>state.pageParent[id]||null),nav:state.pages.filter(id=>!isDetailPage(id))}})()`, ctx);
assert.deepEqual(Array.from(flow.modes), ['tab', 'detail', 'detail']);
assert.equal(flow.parents[1], flow.ids[0]);
assert.equal(flow.parents[2], flow.ids[1]);
assert.ok(!flow.nav.includes(flow.ids[1]) && !flow.nav.includes(flow.ids[2]));
const exported = vm.runInContext(`(function(){download=(name,data)=>{globalThis.exported=data};exportHtml();return globalThis.exported})()`, ctx);
assert.ok(exported.includes(`data-page="${flow.ids[1]}"`));
assert.ok(!exported.includes(`data-page-target="${flow.ids[1]}"`));
assert.ok(exported.includes('pageModes=') && exported.includes('id="back"'));
const disabled = vm.runInContext(`(function(){const item=makeItem('button','neon');item.visualState='disabled';return exportElement(item)})()`, ctx);
assert.ok(disabled.includes('state-disabled') && disabled.includes(' disabled'));
console.log('Template flow creation and disabled button export passed.');

